# Generated by Django 4.1.5 on 2023-01-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='page',
            field=models.URLField(default='', max_length=250),
        ),
    ]
